version: '3.2'
services:
  chall:
    build: .
    volumes:
      - type: bind
        source: ./ro
        target: /home/chall/service/ro
        read_only: true
      - type: bind
        source: ./rw
        target: /home/chall/service/rw
      - type: bind
        source: ./append
        target: /home/chall/service/append
    ports:
      - "6666:6666"
