version: '3.2'
services:
  diamonds:
    build: ./service
    volumes:
      - type: bind
        source: ./service/ro
        target: /home/chall/service/ro
        read_only: true
      - type: bind
        source: ./service/rw
        target: /home/chall/service/rw
      - type: bind
        source: ./service/rr
        target: /home/chall/service/rr
    ports:
      - "6666:6666"
