version: "2.2"

networks:
  prosopagnosia:
    driver: bridge


services:
  gateway:
#    restart: always
    container_name: prosopagnosia_gateway
    image: prosopagnosia_gateway
    privileged: true
    build:
      context: .
      dockerfile: ./docker/gateway/Dockerfile
    tty: true
    volumes:
      - prosopagnosia_back_data:/var/www/roms
    ports:
      - "20002:15345"
    networks:
      -  prosopagnosia
    # ulimits:
    #   nofile:
    #     soft: 12000
    #     hard: 12000

  postgres:
    image: postgres:13.2-alpine
#    restart: always
    container_name: prosopagnosia_postgres
    privileged: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - prosopagnosia_psql_data:/var/lib/postgresql/data
    networks:
      -  prosopagnosia

    # mem_limit: 3G
    # ulimits:
    #   nofile:
    #     soft: 12000
    #     hard: 12000
    # cpus: 1.75
    # pids_limit: 1000

  backend:
    hostname: backend
    container_name: prosopagnosia_backend
    image: prosopagnosia_backend
    build: ./docker/back
#    restart: always
    volumes:
      - prosopagnosia_back_data:/var/prosopagnosia
    depends_on:
      - postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: db
      SVM_STORAGE_PATH: /var/prosopagnosia
    networks:
      -  prosopagnosia
    # mem_limit: 4G
    # ulimits:
    #   nofile:
    #     soft: 12000
    #     hard: 12000
    # cpus: 2
    # pids_limit: 1000

volumes:
  prosopagnosia_psql_data:
  prosopagnosia_back_data:
