version: '3.4'

services:

    ictf_teaminterface:
        image: ictf_teaminterface
        # sysctls:
        #     - net.core.somaxconn=65535
        ports:
            - "80:80"
            - "9100:9100"

        environment:
            - LOGSTASH_ID=teaminterface