services:
  hermicache:
    build:
      context: .
    image: hermicache
    container_name: hermicache
    restart: always
    entrypoint: julia
    command: Server.jl
    depends_on:
      - hermicache_redis
    environment:
      REDIS_HOST: hermicache_redis
      ENV: PROD
    mem_limit: 1G
    memswap_limit: 1G
    cpu_count: 1
    pids_limit: 128
    ulimits:
      nofile:
        soft: 32768
        hard: 32768
    ports:
      - 20005:8080
  hermicache_redis:
    container_name: hermicache_redis
    image: redis:7.0.5-alpine
    restart: unless-stopped
    hostname: redis
    volumes:
      - vault:/vault/books
    mem_limit: 1G
    memswap_limit: 1G
    cpu_count: 1
    pids_limit: 128
    ulimits:
      nofile:
        soft: 8192
        hard: 8192
volumes:
  vault: