#!/usr/bin/env python3
import random
from string import ascii_letters, digits
import sys
import json
import traceback
from nclib import Netcat


def get_flag(ip, port, flag_id, token):
    response = {
        "error": False,
        "payload": {},
    }

    r = Netcat((ip, port))
    r.recvuntil(">")
    r.send("2\n")

    r.recvuntil("backup:")
    r.send(flag_id + "\n")
    r.recvuntil("backup:")

    r.send(token + "\n")
    content = r.recvuntil(">").decode().strip()
    flag = content.split("\n")[1]
    r.send("3\n")
    r.recvuntil("\n")

    r.close()
    response["payload"] = {"flag": flag}

    return response


if __name__ == "__main__":
    try:
        print(
            json.dumps(
                get_flag(sys.argv[1], int(sys.argv[2]), sys.argv[3], sys.argv[4])
            )
        )
    except Exception as e:
        response = {"error": True, "payload": str(e) + "\n" + traceback.format_exc()}
        print(json.dumps(response))
