version: '3.4'

services:

    ictf_logger:
        image: ictf_logger
        hostname: logger
        build:
            dockerfile: ./hephaestus/docker/1_logger/Dockerfile
            context: ../../
