version: '3.4'

services:

    ictf_gamebot:
        image: ictf_gamebot
        hostname: gamebot
        build:
            dockerfile: ./hephaestus/docker/1_gamebot/Dockerfile
            context: ../../
