version: '3.4'

services:

    ictf_router:
        image: ictf_router
        hostname: router
        build:
            dockerfile: ./hephaestus/docker/1_router/Dockerfile
            context: ../../
