version: '3.4'

services:

    ictf_scoreboard:
        image: ictf_scoreboard
        hostname: scoreboard
        build:
            dockerfile: ./hephaestus/docker/1_scoreboard/Dockerfile
            context: ../../
