version: '3.4'

services:

    ictf_database:
        image: ictf_database
        hostname: database
        build:
            dockerfile: ./hephaestus/docker/1_database/Dockerfile
            context: ../../
