version: '3.4'

services:

    ictf_teaminterface:
        image: ictf_teaminterface
        hostname: teaminterface
        build:
            dockerfile: ./hephaestus/docker/1_teaminterface/Dockerfile
            context: ../../
