version: '2.2'

services:
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 8888:80
    depends_on:
      - app
#      - cleaner
#    stop_grace_period: 3s
#    mem_limit: 1G
#    memswap_limit: 1G
#    cpu_count: 1
#    pids_limit: 128
#    ulimits:
#      nofile:
#        soft: 8192
#        hard: 8192

  app:
    build: .
    command: gin --port 8000 run
    restart: always
    volumes:
      - database:/database/
      - ./secret/:/app/jwt_secret/
#    stop_grace_period: 3s
#    mem_limit: 1G
#    memswap_limit: 1G
#    cpu_count: 1
#    pids_limit: 128
#    ulimits:
#      nofile:
#        soft: 8192
#        hard: 8192

#  cleaner:
#    build: cleaner
#    stop_grace_period: 3s
#   mem_limit: 1G
#    memswap_limit: 1G
#    cpu_count: 1
#    pids_limit: 128
#    ulimits:
#      nofile:
#        soft: 8192
#        hard: 8192
#    restart: unless-stopped
#    volumes:
#      - database:/database

volumes:
  database:
#  jwt_secret:
