#!/usr/bin/env python3
import random
from string import ascii_letters, digits
import sys
import json
import traceback
from api import API
from models import *

ALPHA = ascii_letters + digits

def generate_random_string(length:int) -> bytes():
    return ''.join(random.choice(ALPHA) for _ in range(length)).encode()

def generate_user(l:int = 10):
    username = generate_random_string(l)
    password = generate_random_string(l)
    return username, password

def benign(ip, port):
    response = {
        "error": False,
        "payload": {},
    }

    for _ in range(2):
        username1, password1 = generate_user(random.randint(8,15))
        username2, password2 = generate_user(random.randint(8,15))
        name_dialogue = generate_random_string(random.randint(10,22))

        api1 = API(ip, port)
        api1.register(RegisterReq(username=username1, password=password1))
        api1.login(LoginReq(username=username1, password=password1))

        api2 = API(ip, port)
        api2.register(RegisterReq(username=username2, password=password2))
        api2.login(LoginReq(username=username2, password=password2))

        message = generate_random_string(random.randint(10,22))
        create_dialogue_rsp = api1.create_dialogue(CreateDialogueReq(username=username2, name=name_dialogue))

        get_dialogue_rsp = api1.get_dialogue(GetDialogueReq(username=username2))

        if get_dialogue_rsp.name !=  name_dialogue:
            response['error'] = True
            response['payload'] = "ERROR: The name received ({}) does not match the expected one ({})".format(name_dialogue.decode(), get_dialogue_rsp.name.decode())
            return response

        send_msg_rsp = api1.send_msg(SendMsgReq(dialogue_id=create_dialogue_rsp.id, text=message))



    return response


if __name__ == "__main__":
    try:
        print(json.dumps(benign(sys.argv[1], int(sys.argv[2]))))
    except Exception as e:
        response = {
            "error": True,
            "payload": str(e) + "\n" + traceback.format_exc()
        }
        print(json.dumps(response))


