#!/usr/bin/env python3
import json
import sys
import json
import traceback
from api import API
from models import *

def get_flag(ip, port, flag_id, token):
    response = {
        "error": False,
        "payload": {},
    }
    users = json.loads(token)
    username1 = users["username1"]
    password1 = users["password1"]
    username2 = users["username2"]

    api1 = API(ip, port)
    api1.login(LoginReq(username=username1.encode(), password=password1.encode()))
    get_dialogue_rsp = api1.get_dialogue(GetDialogueReq(username=username2.encode()))
    flag = get_dialogue_rsp.name
    response["payload"] = {"flag" : flag.decode()}
    return response


if __name__ == "__main__":
    try:
        print(json.dumps(get_flag(sys.argv[1], int(sys.argv[2]), sys.argv[3], sys.argv[4])))
    except Exception as e:
        response = {
            "error": True,
            "payload": str(e) + "\n" + traceback.format_exc()
        }
        print(json.dumps(response))
