version: '3.4'

services:

    ictf_scoreboard:
        image: ictf_scoreboard
        # sysctls:
        #     - net.core.somaxconn=65535
        ports:
            - "80:80"
            - "9100:9100"
        environment:
            - LOGSTASH_ID=scoreboard
            