---
- name: fail if PRIMER_GUEST_SERVICES_PATH  is not specified
  fail:
    msg: "the teamvm requires PRIMER_GUEST_SERVICES_PATH  to be set"
  when: PRIMER_GUEST_SERVICES_PATH  is not defined

- name: fail if PRIMER_HOST_SERVICES_PATH is not specified
  fail:
    msg: "the teamvm requires PRIMER_HOST_SERVICES_PATH to be set"
  when: PRIMER_HOST_SERVICES_PATH is not defined

- name: fail if PRIMER_SERVICES is not specified
  fail:
    msg: "the teamvm requires PRIMER_SERVICES to be set"
  when: PRIMER_SERVICES is not defined


########################          Setup the MOTD now        ###############################
# Messages for the user #TODO: fix for current version of iCTF, root, self-host, services as docker
- name: motd
  template:
    src: motd.j2
    dest: /etc/motd


# - name: setup ctf user
#   user:
#     name: ctf
#     uid: 31337
#     create_home: yes
#     shell: /bin/bash
#     state: "present"

- name: Add user to sudoers without password
  lineinfile:
    path: /etc/sudoers
    insertafter: '^# Allow members of group sudo to execute any command'
    line: 'ctf ALL=(ALL) NOPASSWD:ALL'
  become: yes
  become_user: root

# - name: Copy the authorized key file from
#   authorized_key:
#     user: "ctf"
#     state: "present"
#     key: "{{ lookup('file', '~/.ssh/id_rsa.pub')}}"

# - name: check ctf user info
#   getent:
#     database: passwd
#     key: ctf

########################    CREATE SERVICE BASE DIRECTORY   ###############################
- name: create service directory
  file:
    path: "{{ PRIMER_GUEST_SERVICES_PATH }}"
    owner: "ctf"
    group: "ctf"
    state: directory
    mode: 0755


########################          DEPLOY THE SERVICES       ###############################
- name: deploy CTF services
  include_role:
    name: deploy_ctf_service
  vars:
    SERVICE_NAME: "{{ item }}"
    DEPLOY_GUEST_SERVICES_PATH : "{{ PRIMER_GUEST_SERVICES_PATH }}"
    DEPLOY_HOST_SERVICES_PATH: "{{ PRIMER_HOST_SERVICES_PATH }}"
    DEPLOY_LOCAL: "{{ PRIMER_LOCAL }}"
  with_items: "{{ PRIMER_SERVICES }}"

# - name: Generate docker-compose.yml
#   template:
#     src: docker-compose.yml.j2
#     dest: "{{ PRIMER_GUEST_SERVICES_PATH }}/docker-compose.yml"
#     owner: "ctf"
#     group: "ctf"

#- name: build service docker files in parallel
#  shell: "docker compose build --parallel"
#  args:
#    chdir: "{{ PRIMER_GUEST_SERVICES_PATH }}"
#  when: PRIMER_LOCAL == false

########################    SETUP bindfs for append-only    ###############################
# - name: setup bindfs for the append only dir
#   lineinfile:
#     path: /etc/fstab
#     line: "{{ PRIMER_GUEST_SERVICES_PATH }}/{{item}}/append {{ PRIMER_GUEST_SERVICES_PATH }}/{{item}}/append fuse.bindfs force-user=root,perms=u=rwD:g=r:dg=rwx:o=D"
#   with_items: "{{ PRIMER_SERVICES }}"
#   when: PRIMER_LOCAL == false

########################            CLEAN UP YO SHIT        ###############################
#- name: prune docker cache
#  shell: docker system prune --volumes -f
#  when: PRIMER_LOCAL == false

- name: copy start dock-compose file
  copy:
    src: start_docker.sh
    dest: /opt/ictf/services
    owner: ctf
    group: ctf
    mode: 0755

- name: Change owner and group of the folder recursively
  file:
    path: /opt/ictf/services/
    owner: ctf
    group: chall
    recurse: yes